src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from .views import (home_view, login_view, shop_view, detail_view, cart_view, blog_view, checkout_view,
blog_single_view, contact_view, page_404_view)

from carts.views import cart_home

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^shop-fbv/$', shop_view, name='shop'),
    url(r'^product-fbv/(?P<pk>\d+)/$', detail_view, name='product'),
    # url(r'^cart/$', cart_view, name='cart'),
    url(r'^cart/$', cart_home, name='cart'),
    url(r'^login/$', login_view, name='login'),
    url(r'^contact/$', contact_view, name='contact'),
    url(r'^blog/$', blog_view, name='blog'),
    url(r'^blog-single/$', blog_single_view, name='blog-single'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^404/$', page_404_view, name='404'),

    
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    # url(r'^shop/$', ProductListView.as_view()),
    # url(r'^product/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^product/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (
            ProductListView,
            # ProductDetailView,
            # ProductFeaturedListView,
            # ProductFeaturedDetailView,
            ProductDetailSlugView,

            )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    # url(r'^product/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name="detail"),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
]

src/search/urls.py
from django.conf.urls import url

from .views import (
            SearchProductView,
            )

urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),
]

src/templates/base/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>

     {% include 'base/css.html' %}

    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
{% include "base/header.html" %}

  {% block content %}{% endblock %}
  
{% include "base/footer.html" %}

{% include 'base/js.html' %}
</body>
</html>

src/templates/base/css.html
{% load static %}
<link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
<link href='{%  static "css/font-awesome.min.css" %}' rel="stylesheet">
<link href='{%  static "css/prettyPhoto.css" %}' rel="stylesheet">
<link href='{%  static "css/price-range.css" %}' rel="stylesheet">
<link href='{%  static "css/animate.css" %}' rel="stylesheet">
<link href='{% static "css/main.css" %}' rel="stylesheet">
<link href='{%  static "css/responsive.css" %}' rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->

src/templates/base/footer.html
{% load static %}
<footer id="footer"><!--Footer-->
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="companyinfo">
            <h2><span>e</span>-shopper</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <img src="images/home/iframe1.png" alt="" />
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <img src="images/home/iframe2.png" alt="" />
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <img src="images/home/iframe3.png" alt="" />
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <img src="images/home/iframe4.png" alt="" />
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="address">
            <img src="images/home/map.png" alt="" />
            <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Service</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Online Help</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Order Status</a></li>
              <li><a href="#">Change Location</a></li>
              <li><a href="#">FAQ’s</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Quock Shop</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">T-Shirt</a></li>
              <li><a href="#">Mens</a></li>
              <li><a href="#">Womens</a></li>
              <li><a href="#">Gift Cards</a></li>
              <li><a href="#">Shoes</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Policies</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Terms of Use</a></li>
              <li><a href="#">Privecy Policy</a></li>
              <li><a href="#">Refund Policy</a></li>
              <li><a href="#">Billing System</a></li>
              <li><a href="#">Ticket System</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Company Information</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#">Store Location</a></li>
              <li><a href="#">Affillate Program</a></li>
              <li><a href="#">Copyright</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
              <p>Get the most recent updates from <br />our site and be updated your self...</p>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
        <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
      </div>
    </div>
  </div>

</footer><!--/Footer-->

src/templates/base/header.html
{% load static %}
{% url 'home' as home_url %}
{% url 'shop' as shop_url %}
{% url 'blog' as blog_url %}
{% url 'login' as login_url %}
{% url 'checkout' as checkout_url %}
{% url 'cart' as cart_url %}
{% url 'contact' as contact_url %}
{% url '404' as 404_url %}




{% for header in object_list %}

<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> {{header.phone}}</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> {{header.email}}</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							{% if header.logo %}
							<a href="{{home_url}}"><img src="{{ header.logo.url }}" alt=""></a>
							{% else %}
							<a href="{{home_url}}">Ecommerce</a>
							{% endif %}
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>

							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canadian Dollar</a></li>
									<li><a href="#">Pound</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="{{checkout_url}}"
									class="{% if request.path == checkout_url %}active{% endif %}"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="{{cart_url}}"
									class="{% if request.path == cart_url %}active{% endif %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								{% if request.user.is_authenticated %}
								<li><a href="{{login_url}}"
									class="{% if request.path == login_url %}active{% endif %}">
									<i class="fa fa-lock"></i> Logout</a></li>
								{% else %}
								<li><a href="{{login_url}}"
									class="{% if request.path == login_url %}active{% endif %}">
									<i class="fa fa-lock"></i> Login</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{{home_url}}"  class="{% if request.path == home_url %}active{% endif %}" >
									{{ header.pages}}</a></li>
								<li class="dropdown"><a href="{{shop_url}}"
									class="{% if request.path == shop_url %}active{% endif %}">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'products:list' %}">Products</a></li>
										<li><a href="{% url 'products:list' %}"
											class="{% if request.path == shop_url %}active{% endif %}">Product Details</a></li>
										<li><a href="{{checkout_url}}"
											class="{% if request.path == checkout_url %}active{% endif %}">Checkout</a></li>
										<li><a href="{{cart_url}}"
											class="{% if request.path == cart_url %}active{% endif %}">Cart</a></li>
										<li><a href="{{login_url}}"
											class="{% if request.path == login_url %}active{% endif %}">Login</a></li>
                                    </ul>
                                </li>
								<li class="dropdown"><a href="{{blog_url}}"
									class="{% if request.path == blog_url %}active{% endif %}">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{{blog_url}}">Blog List</a></li>
										<li><a href="{{blog_single_url}}"
											class="{% if request.path == blog_single_url %}active{% endif %}">Blog Single</a></li>
                                    </ul>
                                </li>
								<li><a href="{{404_url}}" class="{% if request.path == 404_url %}active{% endif %}">404</a></li>
								<li><a href="{{contact_url}}" class="{% if request.path == contact_url %}active{% endif %}">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
					{% include 'search/snippets/search-form.html' %}
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
{% endfor %}

src/templates/base/js.html
{% load static %}
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "js/bootstrap.min.js" %}'></script>
<script src='{% static "js/jquery.scrollUp.min.js" %}'></script>
<script src='{% static "js/price-range.js" %}'></script>
<script src='{% static "js/jquery.prettyPhoto.js" %}'></script>
<script src='{% static "js/main.js" %}'></script>